apiVersion: v1
kind: Pod
metadata:
  name: simple-server
spec:
  terminationGracePeriodSeconds: 10
  containers:
  - name: simple-server
    image: simple-server:v1
    ports:
    - containerPort: 8080