apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simple-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-server
  template:
    metadata:
      name: simple-server
      labels:
        app: simple-server
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: simple-server
          image: simple-server:v2
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
