apiVersion: v1
kind: Service
metadata:
    name: simple-server-service
spec:
    selector:
        app: simple-server
    type: NodePort
    ports:
    -   nodePort: 31234
        port: 8080
        protocol: TCP
        targetPort: 8080